import Link from 'next/link';
import Image from 'next/image';
import { ArrowDown, ArrowLeft, ArrowUpLeft, Globe2 } from 'lucide-react';
import { entities } from '@/lib/entities';

function Mark(){return <span className="brand-mark" aria-hidden="true"><span/><span/><span/><span/></span>}
export default function ArabicHome(){return <main dir="rtl" className="arabic-home">
  <section className="hero" id="top">
    <header className="site-header shell"><Link className="wordmark" href="/ar"><Mark/><span>ثرى</span></Link><nav className="desktop-nav"><a href="#ecosystem">منظومة ثرى</a><a href="#about">عن ثرى</a><a href="#impact">الأثر</a><a href="#opportunities">الفرص</a></nav><div className="header-actions"><Link className="language" href="/"><Globe2 size={15}/>English</Link><a className="contact-link" href="#contact">ابدأ محادثة <ArrowUpLeft size={15}/></a></div></header>
    <div className="hero-grid" aria-hidden="true"><div className="arch arch-one"/><div className="arch arch-two"/><div className="sun-disc"/><div className="hero-noise"/></div>
    <div className="hero-content shell"><p className="eyebrow">منظومة متكاملة لريادة الأعمال والاستثمار</p><h1>المنظومة بأكملها،<br/><em>من البداية إلى النهاية.</em></h1><div className="hero-bottom"><p>وُلدت في عجمان. صُممت لتحوّل الطموح إلى أعمال، وتربط رأس المال بالفرص، وتصنع قيمة تدوم.</p><a className="circle-link" href="#ecosystem"><ArrowDown/></a></div></div>
    <div className="hero-meta shell"><span>25.4052° شمالاً</span><span>عجمان، الإمارات العربية المتحدة</span><span>55.5136° شرقاً</span></div>
  </section>
  <section className="ecosystem-intro shell" id="ecosystem"><div className="section-kicker"><span>01</span><span>منصة واحدة مترابطة</span></div><div className="intro-copy"><h2>ليست مجرد حاضنة.</h2><p>تجمع ثرى كل ما تحتاجه الأعمال للبناء والتمويل والنمو ضمن منظومة محلية واحدة صُممت حول الرحلة، لا حول الكيانات المنفصلة.</p></div><div className="entity-grid">{entities.map((entity,index)=><Link className="entity-card" href={`/ar/ecosystem/${entity.slug}`} key={entity.slug}><span className="entity-number">0{index+1}</span><div><h3>{entity.name.ar}</h3><p>{entity.eyebrow.ar}</p></div><ArrowUpLeft className="entity-arrow" size={20}/></Link>)}</div></section>
  <section className="journey" id="about"><div className="shell journey-inner"><div className="section-kicker light"><span>02</span><span>من الطموح إلى الأثر</span></div><div className="journey-heading"><h2>رحلة واحدة.<br/><em>كل القدرات.</em></h2><p>تعمل كيانات ثرى كنظام واحد مترابط، يلتقي بالأعمال أينما كانت ويساعدها على التقدم.</p></div><ol className="journey-steps">{['تواصل','اختبار','بناء','تشغيل','تمويل','توسع','مساهمة'].map((s,i)=><li key={s}><span>0{i+1}</span><strong>{s}</strong></li>)}</ol></div></section>
  <section className="place-story shell" id="impact"><div className="place-image"><Image src="/images/thara-courtyard.png" alt="فناء معماري يجمع بين المواد الدافئة وضيافة المجلس" fill sizes="(max-width: 900px) 100vw, 58vw"/><span>وُلدت هنا. لتنطلق أبعد.</span></div><div className="place-copy"><div className="section-kicker"><span>03</span><span>من عجمان</span></div><h2>راسخة في المكان.<br/>منفتحة على الإمكانات.</h2><p>تمنح عجمان ثرى شخصيتها: ريادية، مترابطة وإنسانية. ومن هنا نبني فرصاً تمتد أهميتها عبر الإمارات وما بعدها.</p><a className="text-link" href="#contact">اكتشف قصتنا <ArrowUpLeft size={18}/></a></div></section>
  <section className="audiences shell" id="opportunities"><div className="section-kicker"><span>04</span><span>اعثر على مسارك</span></div><div className="audience-head"><h2>ماذا تريد<br/>أن تبني؟</h2><p>اختر المسار الأقرب إليك، وسنصلك بالجزء المناسب من منظومة ثرى.</p></div><div className="audience-list">{['رواد الأعمال والشركات الناشئة','الشركات الصغيرة والمتوسطة','المستثمرون','الشركات الكبرى','الجهات الحكومية والمؤسسات','شركاء المنظومة'].map((a,i)=><a href="#contact" key={a}><span>0{i+1}</span><strong>{a}</strong><ArrowUpLeft/></a>)}</div></section>
  <section className="closing" id="contact"><div className="shell closing-inner"><p>ابنِ الفرصة القادمة مع ثرى</p><h2>لنصنع معاً<br/><em>ما يأتي بعد ذلك.</em></h2><a className="closing-button" href="mailto:hello@thara.ae">ابدأ محادثة <ArrowUpLeft/></a></div></section>
  <footer className="footer"><div className="shell footer-grid"><div><Link className="wordmark footer-brand" href="/ar"><Mark/><span>ثرى</span></Link><p>المنظومة بأكملها، من البداية إلى النهاية.<br/>تنطلق من عجمان.</p></div><div><span className="footer-label">استكشف</span><a href="#ecosystem">منظومة ثرى</a><a href="#about">عن ثرى</a><a href="#impact">الأثر</a></div><div><span className="footer-label">تواصل</span><a href="mailto:hello@thara.ae">الاستفسارات العامة</a><a href="mailto:partnerships@thara.ae">الشراكات</a></div></div><div className="shell footer-bottom"><span>© 2026 ثرى</span><span>عجمان، الإمارات العربية المتحدة</span><span>الخصوصية · الشروط</span></div></footer>
</main>}
